const movieList = [
  { index: 1, title: 'Citizen Kane', key: 'citizen-kane' },
  { index: 2, title: 'The Godfather', key: 'the-godfather-part-i' },
  { index: 3, title: 'Casablanca', key: 'casablanca' },
  { index: 4, title: 'Raging Bull', key: 'raging-bull' },
  { index: 5, title: 'Singin\' in the Rain', key: 'singin-in-the-rain' },
  { index: 6, title: 'Gone with the Wind', key: 'gone-with-the-wind' },
  { index: 7, title: 'Lawrence of Arabia', key: 'lawrence-of-arabia' },
  { index: 8, title: 'Schindler\'s List', key: 'schindlers-list' },
  { index: 9, title: 'Vertigo', key: 'vertigo' },
  { index: 10, title: 'The Wizard of Oz', key: 'the-wizard-of-oz' },
  { index: 11, title: 'City Lights', key: 'charlie-chaplin-city-lights' },
  { index: 12, title: 'The Searchers', key: 'the-searchers' },
  { index: 13, title: 'Star Wars', key: 'star-wars-episode-iv-a-new-hope' },
  { index: 14, title: 'Psycho', key: 'psycho' },
  { index: 15, title: '2001: A Space Odyssey', key: 'how-the-solar-system-was-won' },
  { index: 16, title: 'Sunset Boulevard', key: 'sunset-blvd' },
  { index: 17, title: 'The Graduate', key: 'the-graduate' },
  { index: 18, title: 'The General', key: 'the-general' },
  { index: 19, title: 'On the Waterfront', key: 'on-the-waterfront' },
  { index: 20, title: 'It\'s a Wonderful Life', key: 'frank-capras-its-a-wonderful-life' },
  { index: 21, title: 'Chinatown', key: 'chinatown' },
  { index: 22, title: 'Some Like It Hot', key: 'some-like-it-hot' },
  { index: 23, title: 'The Grapes of Wrath', key: 'the-grapes-of-wrath' },
  { index: 24, title: 'E.T.: The Extra-Terrestrial', key: 'e-t-the-extra-terrestrial' },
  { index: 25, title: 'To Kill a Mockingbird', key: 'to-kill-a-mockingbird' },
  { index: 26, title: 'Mr Smith Goes to Washington', key: 'frank-capras-mr-smith-goes-to-washington' },
  { index: 27, title: 'High Noon', key: 'high-noon' },
  { index: 28, title: 'All About Eve', key: 'all-about-eve' },
  { index: 29, title: 'Double Indemnity', key: 'double-indemnity' },
  { index: 30, title: 'Apocalypse Now', key: 'apocalypse-now-redux' },
  { index: 31, title: 'The Maltese Falcon', key: 'the-maltese-falcon' },
  { index: 32, title: 'The Godfather Part II', key: 'the-godfather-part-ii' },
  { index: 33, title: 'One Flew Over the Cuckoo\'s Nest', key: 'one-flew-over-the-cuckoos-nest' },
  { index: 34, title: 'Snow White and the Seven Dwarfs', key: 'snow-white-and-the-seven-dwarfs' },
  { index: 35, title: 'Annie Hall', key: 'annie-hall' },
  { index: 36, title: 'The Bridge on the River Kwai', key: 'the-bridge-on-the-river-kwai' },
  { index: 37, title: 'The Best Years of Our Lives', key: 'the-best-years-of-our-lives' },
  { index: 38, title: 'The Treasure of the Sierra Madre', key: 'the-treasure-of-the-sierra-madre' },
  { index: 39, title: 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', key: 'dr-strangelove-or-how-i-learned-to-stop-worrying-and-love-the-bomb' },
  { index: 40, title: 'The Sound of Music', key: 'the-sound-of-music' },
  { index: 41, title: 'King Kong (1933)', key: 'king-kong-1933' },
  { index: 42, title: 'Bonnie and Clyde', key: 'bonnie-and-clyde' },
  { index: 43, title: 'Midnight Cowboy', key: 'midnight-cowboy' },
  { index: 44, title: 'The Philadelphia Story', key: 'the-philadelphia-story' },
  { index: 45, title: 'Shane', key: 'shane' },
  { index: 46, title: 'It Happened One Night', key: 'it-happened-one-night' },
  { index: 47, title: 'A Streetcar Named Desire', key: 'a-streetcar-named-desire' },
  { index: 48, title: 'Rear Window (1954)', key: 'alfred-hitchcocks-rear-window' },
  { index: 49, title: 'Intolerance (1916)', key: 'intolerance-loves-struggle-throughout-the-ages' },
  { index: 50, title: 'The Lord of the Rings: The Fellowship of the Ring', key: 'lord-of-the-rings-i-the-fellowship-of-the-ring' },
  { index: 51, title: 'West Side Story (1961)', key: 'west-side-story' },
  { index: 52, title: 'Taxi Driver', key: 'taxi-driver' },
  { index: 53, title: 'The Deer Hunter', key: 'the-deer-hunter' },
  { index: 54, title: 'M*A*S*H', key: 'm-a-s-h' },
  { index: 55, title: 'North by Northwest', key: 'north-by-northwest' },
  { index: 56, title: 'Jaws', key: 'jaws' },
  { index: 57, title: 'Rocky', key: 'rocky' },
  { index: 58, title: 'The Gold Rush', key: 'the-gold-rush' },
  { index: 59, title: 'Nashville', key: 'nashville' },
  { index: 60, title: 'Duck Soup', key: 'marx-brothers-duck-soup' },
  { index: 61, title: 'Sullivan\'s Travels', key: 'sullivans-travels' },
  { index: 62, title: 'American Graffiti', key: 'american-graffiti' },
  { index: 63, title: 'Cabaret', key: 'cabaret' },
  { index: 64, title: 'Network', key: 'network' },
  { index: 65, title: 'The African Queen', key: 'the-african-queen' },
  { index: 66, title: 'Raiders of the Lost Ark', key: 'indiana-jones-and-the-raiders-of-the-lost-ark' },
  { index: 67, title: 'Who\'s Afraid of Virginia Woolf?', key: 'whos-afraid-of-virginia-woolf' },
  { index: 68, title: 'Unforgiven', key: 'unforgiven' },
  { index: 69, title: 'Tootsie', key: 'tootsie' },
  { index: 70, title: 'A Clockwork Orange', key: 'a-clockwork-orange' },
  { index: 71, title: 'Saving Private Ryan', key: 'saving-private-ryan' },
  { index: 72, title: 'The Shawshank Redemption', key: 'the-shawshank-redemption' },
  { index: 73, title: 'Butch Cassidy and the Sundance Kid', key: 'butch-cassidy-and-the-sundance-kid' },
  { index: 74, title: 'The Silence of the Lambs', key: 'the-silence-of-the-lambs' },
  { index: 75, title: 'In the Heat of the Night', key: 'in-the-heat-of-the-night' },
  { index: 76, title: 'Forrest Gump', key: 'forrest-gump' },
  { index: 77, title: 'All the President\'s Men', key: 'all-the-presidents-men' },
  { index: 78, title: 'Modern Times', key: 'modern-times' },
  { index: 79, title: 'The Wild Bunch', key: 'the-wild-bunch' },
  { index: 80, title: 'The Apartment', key: 'the-apartment' },
  { index: 81, title: 'Spartacus', key: 'spartacus' },
  { index: 82, title: 'Sunrise: A Song of Two Humans', key: 'sunrise-a-song-of-two-humans' },
  { index: 83, title: 'Titanic (1997)', key: 'titanic-1997' },
  { index: 84, title: 'Easy Rider', key: 'easy-rider' },
  { index: 85, title: 'A Night at the Opera', key: 'a-night-at-the-opera' },
  { index: 86, title: 'Platoon', key: 'platoon' },
  { index: 87, title: '12 Angry Men', key: '12-angry-men' },
  { index: 88, title: 'Bringing Up Baby', key: 'la-fiera-de-mi-nina' },
  { index: 89, title: 'The Sixth Sense', key: 'the-sixth-sense' },
  { index: 90, title: 'Swing Time', key: 'swing-time' },
  { index: 91, title: 'Sophie\'s Choice', key: 'sophies-choice' },
  { index: 92, title: 'Goodfellas', key: 'goodfellas' },
  { index: 93, title: 'The French Connection', key: 'the-french-connection' },
  { index: 94, title: 'Pulp Fiction', key: 'pulp-fiction' },
  { index: 95, title: 'The Last Picture Show', key: 'the-last-picture-show' },
  { index: 96, title: 'Do the Right Thing', key: 'do-the-right-thing' },
  { index: 97, title: 'Blade Runner', key: 'blade-runner' },
  { index: 98, title: 'Yankee Doodle Dandy', key: 'yankee-doodle-dandy' },
  { index: 99, title: 'Toy Story', key: 'toy-story' },
  { index: 100, title: 'Ben-Hur', key: 'ben-hur' },
];

module.exports = movieList;
